Reduce cxxtools::Json footprint
42ity/fty-security-wallet-rest pull request #25
Opened 2023-06-06 10:39 UTC by sinanyavas-eaton

2023-06-06 11:55 UTC, ericclappier-eaton approved these changes

2023-06-06 12:18 UTC, FrancoisRegisDegott-eaton approved these changes

2023-06-06 12:18 UTC, FrancoisRegisDegott-eaton commented on ecpp/rest_document_GET.ecpp
> +    reply.out() << output.str();
simpler approach:
reply.out() << JSON::writeToString(si, false);

2023-06-06 12:18 UTC, FrancoisRegisDegott-eaton commented on ecpp/rest_documents_GET.ecpp
> +    reply.out() << output.str();
simpler approach:
reply.out() << JSON::writeToString(rootSii, false);

2023-06-06 12:18 UTC, FrancoisRegisDegott-eaton commented on ecpp/rest_documents_POST.ecpp
> +    reply.out() << output.str();
simpler approach:
reply.out() << JSON::writeToString(si, false);

2023-06-08 13:05 UTC, FrancoisRegisDegott-eaton requested changes, later dismissed

2023-06-08 13:05 UTC, FrancoisRegisDegott-eaton commented on ecpp/rest_document_GET.ecpp
> +#include <fty_common_json.h>
#include <cxxtools/serializationinfo.h>  missed

2023-06-08 13:05 UTC, FrancoisRegisDegott-eaton commented on ecpp/rest_documents_POST.ecpp
> +#include <fty_common_json.h>
include cxxtools/serializationinfo.h   ?

2023-06-09 12:47 UTC, merged